version: "3.9"

services:
  web:
    build: .
    ports:
      - "7999:8000"
    depends_on:
      - db
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5437:5432"
    restart: always